name: Build

on:
  push:
    branches: [ master ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  SRC_DIR: /root/
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
        docker run --entrypoint=bash \
          -e GOCACHE=/tmp/.go-build \
          -v ${PWD}:${SRC_DIR}:Z \
          -w ${SRC_DIR}
          golang:1.16
          -c 'test -z $(gofmt -l .)'
    - name: Test
      run: |
        docker run --entrypoint=go \
          -e GOCACHE=/tmp/.go-build \
          -v ${PWD}:${SRC_DIR}:Z \
          -w ${SRC_DIR}
          golang:1.16
          test
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      