name: Build

on:
  push:
    branches: [ master ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    env:
      SRC_DIR: /root/
      REGISTRY: ghcr.io

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Lint
      run: |
        docker run --entrypoint=bash \
          -e GOCACHE=/tmp/.go-build \
          -v ${PWD}:${SRC_DIR}:Z \
          -w ${SRC_DIR} \
          golang:1.17.3 \
          -c 'test -z $(gofmt -l .)'
    - name: Test
      run: |
        docker run --entrypoint=go \
          -e GOCACHE=/tmp/.go-build \
          -v ${PWD}:${SRC_DIR}:Z \
          -w ${SRC_DIR} \
          golang:1.17.3 \
          test
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@a2e02890a0d28163b34ac2e4b575b9264a5ee3e2
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
    - name: Build and push container image
      if: ${{ github.actor != "dependabot[bot]" && github.repository_owner == "oradwell" }}
      uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
