name: Build

on:
  push:
    branches: [ master ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    env:
      SRC_DIR: /root/
      REGISTRY: ghcr.io
      CONTAINER_IMAGE: golang:1.17.7

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Lint
      run: |
        docker run --entrypoint=bash \
          -e GOCACHE=/tmp/.go-build \
          -v ${PWD}:${SRC_DIR}:Z \
          -w ${SRC_DIR} \
          ${CONTAINER_IMAGE} \
          -c 'test -z $(gofmt -l .)'
    - name: Test
      run: |
        docker run --entrypoint=go \
          -e GOCACHE=/tmp/.go-build \
          -v ${PWD}:${SRC_DIR}:Z \
          -w ${SRC_DIR} \
          ${CONTAINER_IMAGE} \
          test
    - name: Log in to the Container registry
      uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Determine tag
      if: ${{ github.actor != 'dependabot[bot]' && github.repository_owner == 'oradwell' }}
      id: tag-determiner
      env:
        PR_NUM: ${{ github.event.pull_request.number }}
      run: |
        SECONDS_IN_YEAR=$(($(date +%s) - $(date +%s --date="$(date +%Y)-01-01 00:00:00 UTC")))
        # Seconds in hex padded to 7 digits
        SECONDS_HEX=$(printf "%.7x\n" ${SECONDS_IN_YEAR})
        # Replace slashes in refname since not supported in image tags
        REF_NAME=$(echo ${GITHUB_REF_NAME} | sed -e 's~/~-~g')
        if [ -n "${PR_NUM}" ]
        then
          REF_NAME=pr-${PR_NUM}
        fi
        echo "::set-output name=tag-name::${REF_NAME}-$(date +%Y)-${SECONDS_HEX}"
    - name: Build and push container image
      if: ${{ github.actor != 'dependabot[bot]' && github.repository_owner == 'oradwell' }}
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.tag-determiner.outputs.tag-name }}
